### ISSUE TITLE
Fix the P-Rep rewards, or remove them

### ISSUE THREAD

**Issue by parrot9design** [ommfinance/openmoneymarket-frontend#66]
The P-Rep rewards displayed on the Vote page are vastly overinflated 

Binance, in the top spot, is shown to be making 103,978 ICX per month. On [iconwat.ch](https://iconwat.ch/) and [ICONLOOK](https://iconlook.io/), it should be around 67,625 ICX per month.

Our earnings in 4th-5th place are also more closely aligned with iconwatch and iconlook. 

We should update the data to use the same formula as these 2 sites, or remove the Earnings column entirely. Showing inflated values is worse than showing none at all.

**Comment by R0bi7** [comment]
Removed.
