### ISSUE TITLE
I can write letters/numbers after unit number "ICX/iUSDC/USDS"

### ISSUE THREAD

**Issue by oDK1** [ommfinance/openmoneymarket-frontend#7]
<img width="243" alt="Screen Shot 2021-06-11 at 12 24 01 PM" src="https://user-images.githubusercontent.com/51342586/121739037-ea10f700-caaf-11eb-9408-705dd40c7e35.png">

Make input section changeable only before the unit "ICX/iUSDC/USDS"

**Comment by parrot9design** [comment]
The behaviour for this is mostly fine. To prevent the ticker from being editable at all will require a bit of refactoring, so I think we just need to improve how it handles certain numbers. 

In the current testnet product, if you enter anything that doesn't make sense, i.e. letters, or numbers after the ticker, it will revert back after a second or two. The only time this doesn't happen is if you enter an amount higher than you have in your wallet:

https://user-images.githubusercontent.com/63842577/122713440-cf156280-d2b9-11eb-98fb-37c8766d8468.mov


In the prototype, it will always revert back as soon as you click away. If we add this behaviour to what's already been implemented, this would be the easiest way to solve it:

https://user-images.githubusercontent.com/63842577/122713505-e5232300-d2b9-11eb-9252-c5c6864b1e6a.mov

**Comment by R0bi7** [comment]
Decision: we split the input in to two parts, input and span.

**Comment by parrot9design** [comment]
I think this is now resolved. Feel free to reopen if there are ongoing issues.
